### ISSUE TITLE
유저 닉네임 변경 시, 불필요한 체크 로직 제거하기

### ISSUE THREAD

**Issue by pmi4202** [SdutyPlus/SdutyPlus#44]
## Description

유저 닉네임 변경하는 로직에서 현재는 전체에서 중복된 값이 있는 확인하고 자기 자신의 원래 닉네임과 같은지 한번더 확인하여 중복여부를 확인하고 있다. 하지만, 전체를 확인할 때, 자기자신도 포함되어 있기 때문에 불필요한 체크가 한 번 더 적용되었다고 생각된다. 차라리 원래 닉네임과 같다면 다른 예외를 던져주는 것이 맞을 것 같다.

## TODO
- [ ] 유저 닉네임 변경 시, 원래 닉네임과 같으면 예외 던지기
- [ ] 유저 닉네임 변경 시, 자신의 닉네임 중복 체크 제거하기
- [ ] 유저 닉네임 변경 시, 원래 닉네임으로 변경 시도 시 던져지는 예외 확인
