### ISSUE TITLE
string.xml에 텍스트 저장해서 쓰기

### ISSUE THREAD

**Issue by nhee-dev** [SdutyPlus/SdutyPlus#54]
## Description
string.xml에 앱에서 표시되는 텍스트들을 저장해서 쓰는 것.
장점은 다음과 같을 것이다.
1. 문장 디테일 변경 시, string.xml만 변경하면 된다.
2. 같은 단어를 재활용할 수 있다.
(우리 서비스는 해당 사항이 없다만, 글로벌 서비스 시에도 장점이 있을 것으로 보임.)

이 작업을 진행할 때는, 같은 Android 팀 내 string.xml name속성 컨벤션을 정하고 리팩토링하자.

## TODO (편하게 변경하셔도 됩니다.)
- [ ] 텍스트가 쓰이는 부분 확인
- [ ] string.xml에 넣을 텍스트 체크 
  - 코드로 텍스트를 보여주는 부분과 아닌 부분을 체크
  - 중복, 여러번 사용할 텍스트 체크
  - 글로벌 동시 번역이 필요한 텍스트 체크
- [ ] string.xml name속성 컨벤션 정하고 문서로 남기기
- [ ] 코드 리뷰할 때 컨벤션 잘 지켰는지, string.xml에 들어간 내용 점검(이후 유지보수, 해석이 편할지 위주로 논의)
